version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - '3000:3000'
    volumes:
    - /home/apps/sweetnspicy/node_modules
    - /Users/sumitpawar/Documents/Work/SweetNSpicy/sweetnspicy:/home/apps/sweetnspicy
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm","start","test"]

